---
- name: Create Proxmox LXC
  hosts: bigprox
  gather_facts: yes

  tasks:
    - name: Install proxmoxer on main host
      ansible.builtin.pip:
        name: proxmoxer

    - name: Print the ssh key and store it to a variable
      delegate_to: localhost
      ansible.builtin.shell: "cat {{ public_key_path }}"
      register: ssh_key

    - name: Create LXC
      community.general.proxmox:
        vmid: "{{ vmid }}"
        node: bigprox
        api_user: root@pam
        api_password: "{{root_password}}"
        api_host: "{{host_ip}}"
        hostname: "{{container_name}}"
        password: "{{container_password}}"
        ostemplate: "local:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
        storage: local-lvm
        unprivileged: 1
        hookscript: "local:snippets/enable_lxc_ssh_hook.sh"
        netif: "{'net0':'name=enp6s0,gw=192.168.1.1,ip={{container_ip}},bridge=vmbr0'}"
        pubkey: "{{ssh_key.stdout}}" # needs to be in format "ssh-rsa ..."

    - name: Start container
      community.general.proxmox:
        vmid: "{{ vmid }}"
        api_user: root@pam
        api_password: "{{root_password}}"
        api_host: "{{host_ip}}"
        state: started

  vars_files:
    - ../../secrets.yaml
    - vars.yaml
